[project]
name = "sql-srs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.0",
    "pandas>=2.2.3",
    "streamlit>=1.42.0",
]
